
- name: install metricbeat GPG key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: add metricbeat apt repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/{{ metricbeat_version }}/apt stable main
    state: present
    filename: metricbeat

- name: install metricbeat
  apt:
    name: metricbeat
    state: latest

- name: configure metricbeat
  template:
    src: metricbeat.yml.j2
    dest: /etc/metricbeat/metricbeat.yml
    mode: "0644"

- name: enable and start metricbeat service
  systemd:
    name: metricbeat
    state: started
    enabled: yes

- name: wait for metricbeat to start up
  wait_for:
    host: localhost
    port: 5066
    state: started
    timeout: 60