
- name: install kibana GPG key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present


- name: add kibana apt repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/{{ kibana_version }}/apt stable main
    state: present
    filename: kibana

- name: install kibana
  apt:
    name: kibana
    state: latest

- name: configure kibana
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    mode: "0644"

- name: enable and start kibana service
  systemd:
    name: kibana
    state: started
    enabled: yes

- name: wait for kibana to start up
  wait_for:
    host: localhost
    port: "{{ kibana_port }}"
    state: started
    timeout: 60